apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: aro-stkirk-bfehg-r2gtq
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
  name: aro-stkirk-bfehg-r2gtq-ocs-eastus3
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: aro-stkirk-bfehg-r2gtq
      machine.openshift.io/cluster-api-machineset: aro-stkirk-bfehg-r2gtq-ocs-eastus3
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: aro-stkirk-bfehg-r2gtq
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: aro-stkirk-bfehg-r2gtq-ocs-eastus3 
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/infra: "" 
          cluster.ocs.openshift.io/openshift-storage: ""
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: aro4 
            publisher: azureopenshift
            resourceID: ''
            sku: aro_48
            version: 48.84.20210630
          kind: AzureMachineProviderSpec
          location: eastus
          metadata:
            creationTimestamp: null
          networkResourceGroup: aro-stkirk-bfehg-eastus
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: aro-stkirk-bfehg-r2gtq
          resourceGroup: aro-stkirk-bfehg-eastus-cluster
          subnet: aro-stkirk-bfehg-worker
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          userDataSecret:
            name: worker-user-data 
          vmSize: Standard_D16s_v3
          vnet: aro-stkirk-bfehg-vnet
          zone: '3'
